### ISSUE TITLE
Multiple layouts

### ISSUE THREAD

**Issue by zontafil** [ris58h/exkeymo-web#7]
Hello,
I own two different keyboard and eaxh needs different key customization. If I try to produce two exkeymo layours, then whenever I install the new one, it replaces (updates) the old one. Is it possible to have two installation in the same system?

thanks,
Filippo Zonta

**Comment by ris58h** [comment]
ExKeyMo produces an app that provides custom keyboard layouts. The app has an application ID that can't be customized. Android treats apps with the same app ID as the same app. That's why you can't have two different ExKeyMo apps installed.

I see 2 options:
- If you need only one layout per keyboard (so 2 layouts total) you can just add the second layout in ExKeyMo.
- Also you can create your custom app based on [custom-keyboard-layout](https://github.com/ris58h/custom-keyboard-layout) project.
